const deck = [
  { name: '1', img: 'aquaman1.jpg' },
  { name: '1', img: 'aquaman2.jpg' },
  { name: '1', img: 'aquaman3.jpg' },
  { name: '1', img: 'aquaman4.jpg' },
  { name: '2', img: 'batman1.jpg' },
  { name: '2', img: 'batman2.jpg' },
  { name: '2', img: 'batman3.jpg' },
  { name: '2', img: 'batman4.jpg' },
  { name: '3', img: 'captain-america1.jpg' },
  { name: '3', img: 'captain-america2.jpg' },
  { name: '3', img: 'captain-america3.jpg' },
  { name: '3', img: 'captain-america4.jpg' },
  { name: '4', img: 'fantastic-four1.jpg' },
  { name: '4', img: 'fantastic-four2.jpg' },
  { name: '4', img: 'fantastic-four3.jpg' },
  { name: '4', img: 'fantastic-four4.jpg' },
  { name: '5', img: 'flash1.jpg' },
  { name: '5', img: 'flash2.jpg' },
  { name: '5', img: 'flash3.jpg' },
  { name: '5', img: 'flash4.jpg' },
  { name: '6', img: 'green-arrow1.jpg' },
  { name: '6', img: 'green-arrow2.jpg' },
  { name: '6', img: 'green-arrow3.jpg' },
  { name: '6', img: 'green-arrow4.jpg' },
  { name: '7', img: 'green-lantern1.jpg' },
  { name: '7', img: 'green-lantern2.jpg' },
  { name: '7', img: 'green-lantern3.jpg' },
  { name: '7', img: 'green-lantern4.jpg' },
  { name: '8', img: 'ironman1.jpg' },
  { name: '8', img: 'ironman2.jpg' },
  { name: '8', img: 'ironman3.jpg' },
  { name: '8', img: 'ironman4.jpg' },
  { name: '9', img: 'spiderman1.jpg' },
  { name: '9', img: 'spiderman2.jpg' },
  { name: '9', img: 'spiderman3.jpg' },
  { name: '9', img: 'spiderman4.jpg' },
  { name: '10', img: 'superman1.jpg' },
  { name: '10', img: 'superman2.jpg' },
  { name: '10', img: 'superman3.jpg' },
  { name: '10', img: 'superman4.jpg' },
  { name: '11', img: 'the-avengers1.jpg' },
  { name: '11', img: 'the-avengers2.jpg' },
  { name: '11', img: 'the-avengers3.jpg' },
  { name: '11', img: 'the-avengers4.jpg' },
  { name: '12', img: 'thor1.jpg' },
  { name: '12', img: 'thor2.jpg' },
  { name: '12', img: 'thor3.jpg' },
  { name: '12', img: 'thor4.jpg' },
  { name: '13', img: 'abc1.jpg' },
  { name: '13', img: 'abc2.jpg' },
  { name: '13', img: 'abc3.jpg' },
  { name: '13', img: 'abc4.jpg' },
];

const game = new Game(deck);
console.log('in game', game.deck);
